GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoibmFuYW4iLCJuYW1lIjoiTmFuIiwiZW1haWwiOiJuYW5AbWFpbC5jb20iLCJpYXQiOjE2NzAwNzQ3NTMsImV4cCI6MTY3MDA3NDg3M30.9Zt_xh0o11frKExF2ATdkAYuAQdPaesJ8bPhqS2DCxs


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "nanan",
    "password": "123"
}

###
GET http://localhost:5000/token