GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJOYW4iLCJlbWFpbCI6Im5hbkBtYWlsLmNvbSIsInVzZXJuYW1lIjoibmFuYW4iLCJpYXQiOjE2NzAxNDgyNDksImV4cCI6MTY3MDE0ODI2NH0.vl6142vb2jGyr_obaaCFsVURBZ8n9U8Cn7Buu3Zeukw


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "nanan",
    "password": "123"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout