GET http://localhost:5000/users 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6InBhaWpvIiwibmFtZSI6IlBhaWpvIiwiZW1haWwiOiJwYWlqb0BtYWlsLmNvbSIsImF2YXRhciI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9wdWJsaWMvdXBsb2Fkcy9kZWZhdWx0LnBuZyIsImlhdCI6MTY3MDM0MTAzOCwiZXhwIjoxNjcwMzQxMTU4fQ.9940CCwAmrqtxIBfjB89MvYP6R2AA5JOsZwPOKyqG8o

### 
POST http://localhost:5000/login 
Content-Type: application/json

{
    "username": "paijo", 
    "password": "123"
}

### 
GET http://localhost:5000/token

### 
DELETE http://localhost:5000/logout

###
POST http://localhost:5000/users 
content-Type: application/json

{
    "name": "Paijo",  
    "email": "paijo@mail.com",     
    "username": "paijo",     
    "confPassword": "123",     
    "password": "123" 
}